
-   datacard_name: "DNN_lessbins_resolved"
    folders:  
        - name: 2016
          basedir: "Full2016v6s5/datacards_datac16"
    phase_spaces:
        -   name: SR_res_ele
            cut: res_sig_mjjincl_ele
            var: DNNoutput_lessbins

        -   name: SR_res_mu
            cut: res_sig_mjjincl_mu
            var: DNNoutput_lessbins

        -   name: wjetCR_res_ele
            cut: res_wjetcr_mjjincl_ele
            var: events

        -   name: wjetCR_res_mu
            cut: res_wjetcr_mjjincl_mu
            var: events

        -   name: topCR_res_ele
            cut: res_topcr_mjjincl_ele
            var: events

        -   name: topCR_res_mu
            cut: res_topcr_mjjincl_mu
            var: events

       
            
-   datacard_name: "DNN_lessbins_boost"
    folders:  
        - name: 2016
          basedir: "Full2016v6s5/datacards_datac16"
    phase_spaces:
    
            -   name: SR_boost_ele
                cut: boost_sig_mjjincl_ele
                var: DNNoutput_lessbins
    
            -   name: SR_boost_mu
                cut: boost_sig_mjjincl_mu
                var: DNNoutput_lessbins
    
            -   name: wjetCR_boost_ele
                cut: boost_wjetcr_mjjincl_ele
                var: events
    
            -   name: wjetCR_boost_mu
                cut: boost_wjetcr_mjjincl_mu
                var: events
    
            -   name: topCR_boost_ele
                cut: boost_topcr_mjjincl_ele
                var: events
    
            -   name: topCR_boost_mu
                cut: boost_topcr_mjjincl_mu
                var: events